fix(client): move WebComponents polyfill to `client/lib` to load it before all the other stuff
The polyfill should be included before anything Polymer-related, otherwise it will cause problems.
It did cause a JS error: `undefined is not a function (webcomponents.js:30)`.
This commit fixes that issue.

More info: Polymer/polymer-tutorial#39